# 🤠 PDS Engineering: Roundup Action
# ==================================
#
# This is a GitHub action that does a "roundup", our fancy term for
# continuous integration and delivery. Yee-haw! 🐄


---

name: '🤠 PDS Engineering: Roundup'
author: 'Sean Kelly <kelly@seankelly.biz>'
branding:
    icon: 'circle'
    color: 'orange'
inputs:
    assembly:
        description: >
            🤠 What kind of roundup are we doing, such as `stable` or `unstable` or
            something else? We default to `unstable`.
        required: false
        default: 'unstable'
    packages:
        description: >
            📦 What packages should be installed prior to starting the roundup? Use
            commas to separate each. These are Alpine Linux package names.
        required: false
        default: ''
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - '--assembly'
        - ${{inputs.assembly}}
        - '--packages'
        - ${{inputs.packages}}
        - '--debug'

...
